import type { MetadataRoute } from 'next';

// Served at /manifest.webmanifest. Makes the candidate's calling card and the
// dashboard installable as a home-screen app on mobile. Icons are generated by
// the app/icons/[size] route (no binary assets in the repo).
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'RoleBoost',
    short_name: 'RoleBoost',
    description: 'Your career. Your AI. Finally heard.',
    start_url: '/',
    display: 'standalone',
    background_color: '#F5F0E8',
    theme_color: '#D97706',
    icons: [
      { src: '/icons/192', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/512', sizes: '512x512', type: 'image/png', purpose: 'any' },
      { src: '/icons/512', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
    ],
  };
}
